# PMID37612267
# exp scRNA-seq workflow
rm(list = ls())
graphics.off()
library(caret)
library(cluster)
library(cowplot)
library(data.table)
library(dplyr)
library(e1071)
library(factoextra)
library(fpc)
library(gg.gap)
library(gganimate)
library(ggExtra)
library(ggplot2)
library(ggsankey)
library(ggsci)
library(ggthemes)
library(ggtree)
library(infercnv)
library(pheatmap)
library(pROC)
library(randomForest)
library(RColorBrewer)
library(readxl)
library(reprex)
library(reshape2)
library(rpca)
library(scales)
library(Seurat)
library(sigminer)
library(tidyverse)
library(treeio)
library(treemapify)
library(tweenr)
library(vegan)
library(monocle)
library(Rtsne)
library(umap)
library(clusterProfiler)
library(org.Hs.eg.db)
library(CellChat)
source("H:/scclone/function0_color.R")
source("H:/scclone/function0_statistic.R")
source("H:/scclone/function1_read_data.R")
source("H:/scclone/function2_signature.R")
source("H:/scclone/function3_make_vaf.R")
source("H:/scclone/function4_cluster.R")
source("H:/scclone/function5_smooth.R")
source("H:/scclone/function6_randomforest.R")
sample2 <- c("P4_1","P6_1")
################################## path ########################################
path = "H:/scclone/PMID32579974_ST"
rna_path = paste0(path,"/paper/ST/GSE144239_RAW/",sample2[1])
mut_path = paste0(path,"/",sample2[1],"/annovar")
work_path = paste0(path,"/",sample2[1],"/work")
dir.create(work_path, showWarnings = F)
dir.create(paste0(work_path,"/0_exp"), showWarnings = F)
dir.create(paste0(work_path,"/1_basic"), showWarnings = F)
dir.create(paste0(work_path,"/2_svm"), showWarnings = F)
dir.create(paste0(work_path,"/3_filter"), showWarnings = F)
dir.create(paste0(work_path,"/4_vaf"), showWarnings = F)
dir.create(paste0(work_path,"/5_smooth"), showWarnings = F)
dir.create(paste0(work_path,"/6_rpca"), showWarnings = F)
dir.create(paste0(work_path,"/7_rf"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure2"), showWarnings = F)

path = "H:/scclone/PMID32579974_ST"
rna_path = paste0(path,"/paper/ST/GSE144239_RAW/",sample2[2])
mut_path = paste0(path,"/",sample2[2],"/annovar")
work_path = paste0(path,"/",sample2[2],"/work")
dir.create(work_path, showWarnings = F)
dir.create(paste0(work_path,"/0_exp"), showWarnings = F)
dir.create(paste0(work_path,"/1_basic"), showWarnings = F)
dir.create(paste0(work_path,"/2_svm"), showWarnings = F)
dir.create(paste0(work_path,"/3_filter"), showWarnings = F)
dir.create(paste0(work_path,"/4_vaf"), showWarnings = F)
dir.create(paste0(work_path,"/5_smooth"), showWarnings = F)
dir.create(paste0(work_path,"/6_rpca"), showWarnings = F)
dir.create(paste0(work_path,"/7_rf"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure2"), showWarnings = F)



