# PMID37612267
# exp scRNA-seq workflow
rm(list = ls())
graphics.off()
library(caret)
library(cluster)
library(cowplot)
library(data.table)
library(dplyr)
library(e1071)
library(factoextra)
library(fpc)
library(gg.gap)
library(gganimate)
library(ggExtra)
library(ggplot2)
library(ggsankey)
library(ggsci)
library(ggthemes)
library(ggtree)
library(infercnv)
library(pheatmap)
library(pROC)
library(randomForest)
library(RColorBrewer)
library(readxl)
library(reprex)
library(reshape2)
library(rpca)
library(scales)
library(Seurat)
library(sigminer)
library(tidyverse)
library(treeio)
library(treemapify)
library(tweenr)
library(vegan)
library(monocle)
library(Rtsne)
library(umap)
library(clusterProfiler)
library(org.Hs.eg.db)
library(CellChat)
source("H:/scclone/function0_color.R")
source("H:/scclone/function0_statistic.R")
source("H:/scclone/function1_read_data.R")
source("H:/scclone/function2_signature.R")
source("H:/scclone/function3_make_vaf.R")
source("H:/scclone/function4_cluster.R")
source("H:/scclone/function5_smooth.R")
source("H:/scclone/function6_randomforest.R")
sample7 <- c("P1","P2","P3","P4","P5","P6","P8")
################################## path ########################################
path = "H:/scclone/PMID38570491_ST"
rna_path = paste0(path,"/paper/ST/",sample7[1])
mut_path = paste0(path,"/",sample7[1],"/annovar")
work_path = paste0(path,"/",sample7[1],"/work")
dir.create(work_path, showWarnings = F)
dir.create(paste0(work_path,"/0_exp"), showWarnings = F)
dir.create(paste0(work_path,"/1_basic"), showWarnings = F)
dir.create(paste0(work_path,"/2_svm"), showWarnings = F)
dir.create(paste0(work_path,"/3_filter"), showWarnings = F)
dir.create(paste0(work_path,"/4_vaf"), showWarnings = F)
dir.create(paste0(work_path,"/5_smooth"), showWarnings = F)
dir.create(paste0(work_path,"/6_rpca"), showWarnings = F)
dir.create(paste0(work_path,"/7_rf"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure2"), showWarnings = F)

path = "H:/scclone/PMID38570491_ST"
rna_path = paste0(path,"/paper/ST/",sample7[3])
mut_path = paste0(path,"/",sample7[3],"/annovar")
work_path = paste0(path,"/",sample7[3],"/work")
dir.create(work_path, showWarnings = F)
dir.create(paste0(work_path,"/0_exp"), showWarnings = F)
dir.create(paste0(work_path,"/1_basic"), showWarnings = F)
dir.create(paste0(work_path,"/2_svm"), showWarnings = F)
dir.create(paste0(work_path,"/3_filter"), showWarnings = F)
dir.create(paste0(work_path,"/4_vaf"), showWarnings = F)
dir.create(paste0(work_path,"/5_smooth"), showWarnings = F)
dir.create(paste0(work_path,"/6_rpca"), showWarnings = F)
dir.create(paste0(work_path,"/7_rf"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure2"), showWarnings = F)

path = "H:/scclone/PMID38570491_ST"
rna_path = paste0(path,"/paper/ST/",sample7[4])
mut_path = paste0(path,"/",sample7[4],"/annovar")
work_path = paste0(path,"/",sample7[4],"/work")
dir.create(work_path, showWarnings = F)
dir.create(paste0(work_path,"/0_exp"), showWarnings = F)
dir.create(paste0(work_path,"/1_basic"), showWarnings = F)
dir.create(paste0(work_path,"/2_svm"), showWarnings = F)
dir.create(paste0(work_path,"/3_filter"), showWarnings = F)
dir.create(paste0(work_path,"/4_vaf"), showWarnings = F)
dir.create(paste0(work_path,"/5_smooth"), showWarnings = F)
dir.create(paste0(work_path,"/6_rpca"), showWarnings = F)
dir.create(paste0(work_path,"/7_rf"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure2"), showWarnings = F)

path = "H:/scclone/PMID38570491_ST"
rna_path = paste0(path,"/paper/ST/",sample7[5])
mut_path = paste0(path,"/",sample7[5],"/annovar")
work_path = paste0(path,"/",sample7[5],"/work")
dir.create(work_path, showWarnings = F)
dir.create(paste0(work_path,"/0_exp"), showWarnings = F)
dir.create(paste0(work_path,"/1_basic"), showWarnings = F)
dir.create(paste0(work_path,"/2_svm"), showWarnings = F)
dir.create(paste0(work_path,"/3_filter"), showWarnings = F)
dir.create(paste0(work_path,"/4_vaf"), showWarnings = F)
dir.create(paste0(work_path,"/5_smooth"), showWarnings = F)
dir.create(paste0(work_path,"/6_rpca"), showWarnings = F)
dir.create(paste0(work_path,"/7_rf"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure2"), showWarnings = F)

path = "H:/scclone/PMID38570491_ST"
rna_path = paste0(path,"/paper/ST/",sample7[6])
mut_path = paste0(path,"/",sample7[6],"/annovar")
work_path = paste0(path,"/",sample7[6],"/work")
dir.create(work_path, showWarnings = F)
dir.create(paste0(work_path,"/0_exp"), showWarnings = F)
dir.create(paste0(work_path,"/1_basic"), showWarnings = F)
dir.create(paste0(work_path,"/2_svm"), showWarnings = F)
dir.create(paste0(work_path,"/3_filter"), showWarnings = F)
dir.create(paste0(work_path,"/4_vaf"), showWarnings = F)
dir.create(paste0(work_path,"/5_smooth"), showWarnings = F)
dir.create(paste0(work_path,"/6_rpca"), showWarnings = F)
dir.create(paste0(work_path,"/7_rf"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure2"), showWarnings = F)

path = "H:/scclone/PMID38570491_ST"
rna_path = paste0(path,"/paper/ST/",sample7[7])
mut_path = paste0(path,"/",sample7[7],"/annovar")
work_path = paste0(path,"/",sample7[7],"/work")
dir.create(work_path, showWarnings = F)
dir.create(paste0(work_path,"/0_exp"), showWarnings = F)
dir.create(paste0(work_path,"/1_basic"), showWarnings = F)
dir.create(paste0(work_path,"/2_svm"), showWarnings = F)
dir.create(paste0(work_path,"/3_filter"), showWarnings = F)
dir.create(paste0(work_path,"/4_vaf"), showWarnings = F)
dir.create(paste0(work_path,"/5_smooth"), showWarnings = F)
dir.create(paste0(work_path,"/6_rpca"), showWarnings = F)
dir.create(paste0(work_path,"/7_rf"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure"), showWarnings = F)
dir.create(paste0(work_path,"/8_figure2"), showWarnings = F)
